---
- hosts: 192.168.1.79
  vars:
    - httpd_port: 8080
  tasks:
    - name: install apache web server
      package: name=httpd state=present

    - name: install git-client
      package: name=git state=present

    - name: start httpd service
      service: name=httpd state=started 

    - name: download code from git
      git: repo=https://github.com/demoglot/html-samples-doctor.git dest=/var/www/html
  
    - name: copy httpd template
      template: src=/root/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
      notify: restart httpd

    - name: enable firewall service
      firewalld: port=8080/tcp permanent=yes state=enabled

    - name: reload firewall service
      service: name=firewalld state=reloaded

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
